"""Contratos versionados do pipeline de governança documental v4.7."""

DOCUMENT_TYPES = ("MD", "ET", "LI", "FD")
DOCUMENT_SUBTYPES = ("LI_IO", "LI_MATERIALS", "LI_INSTRUMENTS", "LI_CABLES", "FD_DATASHEET", "MD_AUTOMATION")
LI_IO_MODEL_ID = "LI_IO_PETROBRAS_AUTOMACAO_V1_0"
MD_MODEL_ID = "MD_AUTOMATION_PETROBRAS_V1_0"

AGENTS = [
    "DatacenterStructureAgent",
    "DocumentUnderstandingAgent",
    "EvidenceTraceabilityAgent",
    "DocumentLayoutLockAgent",
    "MDTemplateStandardAgent",
    "MDParagraphSpacingLockAgent",
    "MDRevisionGrayLifecycleAgent",
    "MDCurrentRevisionTraceabilityAgent",
    "MDLayoutFingerprintAgent",
    "SheetCountPolicyAgent",
    "CellStyleFingerprintAgent",
    "LIInputOutputStandardAgent",
    "LIInputOutputModelAgent",
    "LITextPatchAgent",
    "DataSheetConsistencyAgent",
    "PaginationIntegrityAgent",
    "CommentTraceabilityAgent",
    "DocumentToolingDiscoveryAgent",
    "PluginRegistryAgent",
    "PluginSecurityAgent",
    "PluginSecurityReviewAgent",
    "VisualQAAgent",
    "MDVisualQAAgent",
    "AssetFunctionIOAgent",
    "FunctionalNamingAgent",
    "SymbolComplianceAgent",
    "SignalIntegrityAgent",
    "InterlockAgent",
    "RedundancyAgent",
    "CrossDisciplineAgent",
    "MemoryRegressionAgent",
    "PipelineVersionAgent",
]

GOLDEN_CHECKS = {
    "document_layout_immutable": True,
    "document_text_only_edit": True,
    "pagination_dynamic": True,
    "md_model_required": True,
    "md_paragraph_spacing_immutable": True,
    "md_line_spacing_immutable": True,
    "md_font_immutable": True,
    "md_font_size_immutable": True,
    "md_clear_legacy_gray": True,
    "md_current_revision_gray_only": True,
    "md_current_gray_continuous": True,
    "md_toc_current_revision_marking": True,
    "md_render_all_pages": True,
    "md_inspect_all_pages": True,
    "sheet_count_target_driven": True,
    "plugin_auto_install_forbidden": True,
}

MD_POLICY = {
    "model_id": MD_MODEL_ID,
    "standard": "governance/MD_AUTOMATION_STANDARD_v1_0.md",
    "prompt": "governance/PROMPT_MESTRE_MD_AUTOMACAO_v1_0.md",
    "registry": "datacenter/MD_AUTOMATION_STANDARD.json",
    "data_sheet": "datasheet/MD_AUTOMATION_DATA_SHEET.json",
    "script": "pipeline/md_revision_standard.py",
    "target_document_is_physical_matrix_on_revision": True,
    "canonical_model_is_presentation_reference": True,
    "text_only": True,
    "paragraph_spacing_immutable": True,
    "line_spacing_immutable": True,
    "indentation_immutable": True,
    "tabs_immutable": True,
    "font_immutable": True,
    "font_size_immutable": True,
    "style_immutable": True,
    "tables_immutable": True,
    "sections_immutable": True,
    "headers_footers_immutable": True,
    "images_geometry_immutable": True,
    "revision_gray": "D9D9D9",
    "clear_legacy_gray_before_marking": True,
    "current_revision_only": True,
    "current_change_map_required": True,
    "shade_all_text_runs_in_current_block": True,
    "artificial_spacing_for_gray_forbidden": True,
    "toc_changed_entries_gray": True,
    "render_all_pages": True,
    "inspect_all_pages": True,
    "quality_mode": "BLOCK_ON_ANY_FAILURE",
}

AGENT_CONTRACTS = {
    "DatacenterStructureAgent": {
        "registries": ["datacenter/LI_IO_STANDARD.json", "datacenter/MD_AUTOMATION_STANDARD.json"],
        "document_template_registry_required": True,
        "preserve_source_template_fingerprint": True,
        "preserve_output_fingerprint": True,
        "record_render_evidence": True,
        "public_repository_binary_forbidden": True,
    },
    "DocumentLayoutLockAgent": {
        "block_on_layout_change": True,
        "allow_text_only": True,
        "allow_dynamic_pagination": True,
        "allow_approved_images_only_when_explicit": True,
    },
    "MDTemplateStandardAgent": MD_POLICY,
    "MDParagraphSpacingLockAgent": {
        "compare_pPr_before_after": True,
        "ignore_only_current_revision_run_shading": True,
        "block_spacing_before_after_change": True,
        "block_line_spacing_change": True,
        "block_indent_change": True,
        "block_tab_change": True,
    },
    "MDRevisionGrayLifecycleAgent": {
        "clear_legacy_D9D9D9": True,
        "mark_current_revision_only": True,
        "change_map_is_source_of_truth": True,
        "shade_all_text_runs": True,
        "include_existing_interword_spaces": True,
        "forbid_whitespace_insertion_for_visual_fill": True,
    },
    "MDCurrentRevisionTraceabilityAgent": {
        "comment_anchor_note_page_action_required": True,
        "technical_evidence_required": True,
        "changed_sections_required": True,
        "toc_marking_consistency_required": True,
    },
    "MDLayoutFingerprintAgent": {
        "validate_paragraph_properties": True,
        "validate_tables_rows_cells": True,
        "validate_sections": True,
        "validate_styles_fonts_sizes": True,
        "validate_headers_footers": True,
        "validate_media_relationships": True,
    },
    "MDVisualQAAgent": {
        "canonical_renderer_required": True,
        "render_all_pages": True,
        "inspect_all_pages_100_percent": True,
        "block_on_overlap_clipping_spacing_drift_gray_gap": True,
    },
    "DataSheetConsistencyAgent": {
        "data_sheets": ["datasheet/LI_IO_DATA_SHEET.json", "datasheet/MD_AUTOMATION_DATA_SHEET.json"],
        "validate_text_against_reference_drawings": True,
        "cross_check_md_et_fd_li_de": True,
    },
}
