"""Contratos versionados do pipeline de governança documental v4.6."""

DOCUMENT_TYPES = ("MD", "ET", "LI", "FD")
DOCUMENT_SUBTYPES = ("LI_IO", "LI_MATERIALS", "LI_INSTRUMENTS", "LI_CABLES", "FD_DATASHEET")
LI_IO_MODEL_ID = "LI_IO_PETROBRAS_AUTOMACAO_V1_0"

AGENTS = [
    "DatacenterStructureAgent",
    "DocumentUnderstandingAgent",
    "EvidenceTraceabilityAgent",
    "DocumentLayoutLockAgent",
    "SheetCountPolicyAgent",
    "CellStyleFingerprintAgent",
    "LIInputOutputStandardAgent",
    "LIInputOutputModelAgent",
    "LITextPatchAgent",
    "DataSheetConsistencyAgent",
    "PaginationIntegrityAgent",
    "CommentTraceabilityAgent",
    "DocumentToolingDiscoveryAgent",
    "PluginRegistryAgent",
    "PluginSecurityAgent",
    "PluginSecurityReviewAgent",
    "VisualQAAgent",
    "AssetFunctionIOAgent",
    "FunctionalNamingAgent",
    "SymbolComplianceAgent",
    "SignalIntegrityAgent",
    "InterlockAgent",
    "RedundancyAgent",
    "CrossDisciplineAgent",
    "MemoryRegressionAgent",
    "PipelineVersionAgent",
]

GOLDEN_CHECKS = {
    "symbol_external_mm": 12.0,
    "aspect_ratio": 1.0,
    "functional_name_required": True,
    "memory_regression_required": True,
    "orphan_signal_forbidden": True,
    "cmd_run_fault_available_separate": True,
    "document_layout_immutable": True,
    "document_text_only_edit": True,
    "pagination_dynamic": True,
    "datasheet_layout_immutable": True,
    "li_io_model_required": True,
    "sheet_count_target_driven": True,
    "font_signature_required": True,
    "font_size_immutable": True,
    "notes_sheet_only": True,
    "final_sheet_ad_hoc_note_forbidden": True,
    "plugin_auto_install_forbidden": True,
}

DOCUMENT_LAYOUT_POLICY = {
    "template_is_visual_master": True,
    "target_is_content_master": True,
    "layout_is_immutable": True,
    "sheet_count_source": "TARGET_DOCUMENT",
    "allowed_changes": [
        "TEXT",
        "TECHNICAL_VALUES",
        "TEXTUAL_QUANTITIES",
        "AUTHORIZED_FORMULAS",
        "APPROVED_IMAGES",
    ],
    "forbidden_changes": [
        "MARGINS",
        "TABLE_GEOMETRY",
        "COLUMN_WIDTHS",
        "ROW_HEIGHTS",
        "MERGES",
        "BORDERS",
        "FILLS",
        "STYLES",
        "FONTS",
        "FONT_SIZES",
        "STRUCTURAL_ALIGNMENT",
        "HEADERS",
        "FOOTERS",
        "LOGO",
        "SIGNATURE",
        "PRINT_AREA",
        "PAGE_ORIENTATION",
        "PAGE_SCALE",
        "SECTION_STRUCTURE",
        "TEMPLATE_SHEET_COUNT_COPY",
    ],
    "dynamic_exceptions": ["PAGE_NUMBER", "TOTAL_PAGES", "TOC_PAGE_REFERENCE"],
}

LI_IO_POLICY = {
    "model_id": LI_IO_MODEL_ID,
    "document_type": "LI",
    "document_subtype": "LI_IO",
    "sheet_count_source": "TARGET_DOCUMENT",
    "layout_source": "APPROVED_MODEL_OR_TARGET_SOURCE",
    "copy_template_sheet_count": False,
    "preserve_cell_dimensions": True,
    "preserve_merges": True,
    "preserve_borders": True,
    "preserve_fonts": True,
    "preserve_font_sizes": True,
    "preserve_alignment": True,
    "preserve_print_settings": True,
    "text_must_inherit_destination_style": True,
    "notes_sheet_role": "NOTES_SUMMARY_REFERENCES",
    "ad_hoc_note_on_final_sheet": False,
    "render_all_sheets": True,
    "inspect_all_sheets": True,
    "quality_mode": "BLOCK_ON_ANY_FAILURE",
}
LI_IO_STANDARD = LI_IO_POLICY

PLUGIN_POLICY = {
    "discovery_enabled": True,
    "auto_install": False,
    "license_review_required": True,
    "security_review_required": True,
    "maintenance_review_required": True,
    "version_pin_required": True,
    "regression_test_required": True,
    "human_approval_required": True,
}

AGENT_CONTRACTS = {
    "DatacenterStructureAgent": {
        "registry": "datacenter/LI_IO_STANDARD.json",
        "document_template_registry_required": True,
        "preserve_source_template_fingerprint": True,
        "preserve_output_fingerprint": True,
        "register_layout_and_font_signatures": True,
        "record_target_sheet_count": True,
        "record_changed_cells": True,
        "record_render_evidence": True,
        "public_repository_binary_forbidden": True,
        "document_types": DOCUMENT_TYPES,
    },
    "DocumentLayoutLockAgent": {
        "block_on_layout_change": True,
        "allow_text_only": True,
        "allow_authorized_formulas": True,
        "allow_approved_images": True,
        "allow_dynamic_pagination": True,
    },
    "SheetCountPolicyAgent": {
        "source": "TARGET_DOCUMENT",
        "forbid_copy_from_visual_template": True,
        "declared_total_must_match_actual": True,
    },
    "CellStyleFingerprintAgent": {
        "validate_style_ids": True,
        "validate_fonts": True,
        "validate_font_sizes": True,
        "validate_merges": True,
        "validate_dimensions": True,
        "validate_print_settings": True,
    },
    "LIInputOutputStandardAgent": {
        "standard": "governance/LI_IO_STANDARD_v1_0.md",
        "prompt": "governance/PROMPT_MESTRE_LI_ENTRADA_SAIDA_v1_0.md",
        "layout_immutable": True,
        "sheet_count_target_driven": True,
        "pagination_total_equals_sheet_count": True,
        "notes_only_on_notes_sheet": True,
        "full_reference_codes_required": True,
    },
    "LIInputOutputModelAgent": {
        "model_id": LI_IO_MODEL_ID,
        "policy": "LI_IO_POLICY",
        "validate_io_totals": True,
        "validate_full_document_codes": True,
        "forbid_ad_hoc_note_on_final_sheet": True,
    },
    "LITextPatchAgent": {
        "script": "pipeline/apply_li_io_text_patch.py",
        "existing_cells_only": True,
        "preserve_cell_style": True,
        "compare_layout_before_after": True,
        "delete_output_on_critical_finding": True,
    },
    "DataSheetConsistencyAgent": {
        "data_sheet": "datasheet/LI_IO_DATA_SHEET.json",
        "applies_to": ["FD", "LI"],
        "preserve_internal_layout": True,
        "validate_text_against_reference_drawings": True,
        "validate_tags_codes_quantities": True,
        "validate_origin_destination_direction_purpose": True,
        "validate_protocol_interface_level": True,
        "cross_check_md_et_fd_li_de": True,
        "pagination_must_match_final_sheet_count": True,
    },
    "DocumentToolingDiscoveryAgent": {
        "registry": "plugins/document_tooling_registry.json",
        "auto_install": False,
        "scheduled_discovery": True,
        "human_approval_required": True,
    },
    "PluginRegistryAgent": {
        "registry_path": "plugins/document_tooling_registry.json",
        "scheduled_discovery": True,
        "auto_install": False,
    },
    "PluginSecurityAgent": {
        "license_review_required": True,
        "pin_release_or_commit_required": True,
        "sandbox_before_activation": True,
        "block_unapproved_dependencies": True,
    },
    "PluginSecurityReviewAgent": PLUGIN_POLICY,
}
